// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// mem_compress
SEXP mem_compress(SEXP r_content);
RcppExport SEXP gzmem_mem_compress(SEXP r_contentSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type r_content(r_contentSEXP);
    rcpp_result_gen = Rcpp::wrap(mem_compress(r_content));
    return rcpp_result_gen;
END_RCPP
}
// mem_inflate
SEXP mem_inflate(SEXP r_source, SEXP r_guess_size);
RcppExport SEXP gzmem_mem_inflate(SEXP r_sourceSEXP, SEXP r_guess_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type r_source(r_sourceSEXP);
    Rcpp::traits::input_parameter< SEXP >::type r_guess_size(r_guess_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(mem_inflate(r_source, r_guess_size));
    return rcpp_result_gen;
END_RCPP
}
