# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compress a raw vector using gz compression
#'
#' @param r_content raw vector of data to compress
#' @return Raw vector of compressed data
#' @export
#' @examples
#' rawToChar(mem_inflate(mem_compress(
#'   charToRaw("The quick brown fox jumps over the lazy dog.")), 1000))
mem_compress <- function(r_content, format) {
    .Call('_gzmem_mem_compress', PACKAGE = 'gzmem', r_content, format)
}

#' Inflate a raw vector that was gz compressed
#'
#' @param r_source raw vector of gz compressed data
#' @param r_guess_size your best guess as to the size of uncompressed data. Not ideal,
#'        and this won't be necessary in future releases. Reember, this is a direct
#'        port from the defunct \code{Rcompression} package.\cr
#'        \cr
#'        Aim high as you'll only get back the actual number of bytes
#'        in the uncompressed data.
#' @param Raw vector of expanded data
#' @export
#' @examples
#' rawToChar(mem_inflate(mem_compress(
#'   charToRaw("The quick brown fox jumps over the lazy dog.")), 1000))
mem_inflate <- function(r_source, r_guess_size) {
    .Call('_gzmem_mem_inflate', PACKAGE = 'gzmem', r_source, r_guess_size)
}

